
export const supabaseUrl =  "https://gvltgtssoytkazdsiqgx.supabase.co"

export const supabaseAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2bHRndHNzb3l0a2F6ZHNpcWd4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM2MTg4MDQsImV4cCI6MjA2OTE5NDgwNH0.Kic92RdqPfCQF-UyE9VgtRjy0KyZP0QBDfbqIcZ1sj0"