export const supabaseUrl = "https://jzgsxvwoduhikbcrnexn.supabase.co";
export const supabaseAnonKey =
  "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imp6Z3N4dndvZHVoaWtiY3JuZXhuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MjQyMzY3NjEsImV4cCI6MjAzOTgxMjc2MX0.VzrkZnhIlbQ3qc6tMlsPmutKdEmt9Jl2Lwv8HmJtgZg";
